name: deploy-to-prod

on:
  pull_request:
    branches:
      - 'main'
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure git
      run: |
        git config --global --add safe.directory $(realpath .)
        git config --global user.name 'auto-deploy'
        git config --global user.email 'leonardo_jlo@hotmail.com'

    - name: Install dependencies
      run: |
        git checkout main
        git pull
        npm install

    - name: Build app
      run: 
        npm run build

    - name: Deploy on prod branch
      run: |
        git checkout prod
        cp -R ./dist/. .
        rm -r ./dist
        git commit -am "Deploy"
        git push